services:
  web:
    image: dropme-app
    build:
      context: .
    ports:
      - "8000:80"
    environment:
      - DB_HOST=${db_host}
      - DB_PORT=${db_port}
      - DB_NAME=${db_name}
      - DB_USER=${db_user}
      - DB_PASSWORD=${db_password}
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: ${db_name}
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_password}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
