services:
  web:
    image: dropme-app
    build:
      context: .
    ports:
      - "8000:80"
    environment:
      - DB_HOST=${local_db_host}
      - DB_PORT=${local_db_port}
      - DB_NAME=${local_db_name}
      - DB_USER=${local_db_user}
      - DB_PASSWORD=${local_db_password}
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: ${local_db_name}
      POSTGRES_USER: ${local_db_user}
      POSTGRES_PASSWORD: ${local_db_password}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
