# Generated by Django 4.1.7 on 2023-03-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Format: required, max-length:100", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Format: optional, max-length:500",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "target",
                    models.IntegerField(
                        default=0, help_text="Competition target points"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField(help_text="Competition start date")),
                ("end_date", models.DateField(help_text="Competition end date")),
            ],
        ),
    ]
