# Generated by Django 4.1.7 on 2023-03-12 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("competition_api", "0004_competition_users"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competitionranking",
            options={"ordering": ("-points",)},
        ),
        migrations.AlterField(
            model_name="competition",
            name="users",
            field=models.ManyToManyField(
                related_name="comp_user",
                through="competition_api.CompetitionRanking",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
