# Generated by Django 4.1.7 on 2023-04-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition_api", "0005_alter_competitionranking_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="description_ar",
            field=models.TextField(
                blank=True,
                help_text="arabic translation for description",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="name_ar",
            field=models.CharField(
                blank=True,
                help_text="arabic translation for name field",
                max_length=100,
                null=True,
            ),
        ),
    ]
