# Generated by Django 4.1.7 on 2023-08-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition_api", "0006_competition_description_ar_competition_name_ar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("img", models.ImageField(blank=True, null=True, upload_to="resource")),
                ("link", models.URLField(blank=True, null=True)),
                ("resource_type", models.CharField(max_length=50)),
            ],
        ),
    ]
