# Generated by Django 4.1.7 on 2023-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition_api", "0007_resource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="competition",
            name="description_ar",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="competition",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="competition",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="competition",
            name="name_ar",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="competition",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="competition",
            name="target",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="competitionranking",
            name="points",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
