# Generated by Django 4.1.7 on 2024-10-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='navigation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
