# Generated by Django 4.1.7 on 2024-11-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_remove_notification_body_remove_notification_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notification'),
        ),
    ]
