# Generated by Django 4.1.7 on 2024-12-18 15:58
    
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_notificationimage_alter_notification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(max_length=100, null=True, blank=True)
        ),
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(null=True, blank=True)
        ),
    ]