# Generated by Django 4.1.7 on 2023-02-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Format: required, max-length:200', max_length=200, verbose_name='Machine name')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Format:required', max_digits=9, null=True, verbose_name='Longitude')),
                ('latitdue', models.DecimalField(blank=True, decimal_places=6, help_text='Format:required', max_digits=9, null=True, verbose_name='Latitdue')),
                ('qr_code', models.CharField(help_text='Format: required, max-length:50', max_length=50, verbose_name='Machine Code')),
            ],
            options={
                'verbose_name': 'Machine details',
                'verbose_name_plural': 'Machines details',
            },
        ),
    ]
