# Generated by Django 4.1.7 on 2023-02-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='qr_code',
            field=models.CharField(editable=False, help_text='Format: required, max-length:50', max_length=50, verbose_name='Machine Code'),
        ),
    ]
