# Generated by Django 4.1.7 on 2023-03-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("machine_api", "0003_alter_machine_qr_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="machine",
            options={},
        ),
        migrations.RemoveField(
            model_name="machine",
            name="name",
        ),
        migrations.AddField(
            model_name="machine",
            name="identification_name",
            field=models.CharField(
                default="name",
                help_text="Unique identification name for the machine, max-length:200",
                max_length=200,
                verbose_name="Machine name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="machine",
            name="location",
            field=models.CharField(default="here", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="machine",
            name="place",
            field=models.CharField(default="here", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="machine",
            name="status",
            field=models.CharField(
                choices=[("available", "available"), ("break down", "break down")],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="latitdue",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=25,
                help_text="Latitdue, Format:required",
                max_digits=9,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="machine",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=25,
                help_text="Longitude, Format:required",
                max_digits=9,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="machine",
            name="qr_code",
            field=models.ImageField(blank=True, upload_to="qr_codes"),
        ),
        migrations.CreateModel(
            name="RecycleLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_name", models.CharField(max_length=200)),
                ("bottles", models.PositiveSmallIntegerField(blank=True, default=0)),
                ("cans", models.PositiveSmallIntegerField(blank=True, default=0)),
                ("points", models.IntegerField(blank=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
