# Generated by Django 4.1.7 on 2023-03-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine_api", "0004_alter_machine_options_remove_machine_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="identification_name",
            field=models.CharField(
                help_text="Unique identification name for the machine, max-length:200",
                max_length=200,
                unique=True,
                verbose_name="Machine name",
            ),
        ),
    ]
