# Generated by Django 4.1.7 on 2023-03-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine_api", "0005_alter_machine_identification_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="recyclelog",
            name="in_progess",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recyclelog",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
