# Generated by Django 4.1.7 on 2023-03-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine_api", "0006_recyclelog_in_progess_recyclelog_is_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="recyclelog",
            name="channel_name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
