# Generated by Django 4.1.7 on 2023-03-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine_api", "0007_recyclelog_channel_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="location",
        ),
        migrations.AddField(
            model_name="machine",
            name="city",
            field=models.CharField(help_text="Machine city", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="identification_name",
            field=models.CharField(
                help_text="[required] Unique identification name for the machine, max-length:200",
                max_length=200,
                unique=True,
                verbose_name="Machine name",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="latitdue",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitdue, Format:required",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="place",
            field=models.CharField(
                help_text="machin place inside city", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="status",
            field=models.CharField(
                choices=[("available", "available"), ("breakdown", "breakdown")],
                default="available",
                max_length=20,
            ),
        ),
    ]
