# Generated by Django 4.1.7 on 2023-03-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine_api", "0009_machine_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="latitdue",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
