# Generated by Django 4.1.7 on 2023-04-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine_api", "0014_alter_machine_status_ar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="status_ar",
            field=models.CharField(
                choices=[("متاح", "متاح"), ("لا تعمل", "لا تعمل")],
                default="متاح",
                max_length=20,
            ),
        ),
    ]
