# Generated by Django 4.1.7 on 2023-06-03 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("machine_api", "0016_phonenumber_alter_recyclelog_user_recyclelog_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recyclelog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
