# Generated by Django 4.1.7 on 2023-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine_api", "0018_alter_recyclelog_bottles_alter_recyclelog_cans"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="city",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="city_ar",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="identification_name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="name_ar",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="place",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="place_ar",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
