# Generated by Django 4.1.7 on 2024-11-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_api', '0019_alter_machine_city_alter_machine_city_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='ordering',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
