# Generated by Django 4.1.7 on 2024-11-17 22:48

import django.core.validators
from django.db import migrations, models
import machine_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_api', '0020_machine_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to=machine_api.models.upload_to_videos, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
        ),
    ]
