# Generated by Django 4.1.7 on 2024-11-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_api', '0021_machinevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='name_en',
            field=models.CharField(max_length=200, blank=True, null=True),
        ),
    ]
