# Generated by Django 4.1.7 on 2023-05-27 15:20

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("machine_api", "0022_machine_name_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="recyclelog",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                default="Egypt's International Exhibition Center RVM 1",
                to="machine_api.Machine",
            ),
        ),
    ]