# Generated by Django 4.1.7 on 2023-08-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_cart_active_entry_created_at_entry_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="marketplace.product",
            ),
        ),
    ]
