# Generated by Django 4.1.7 on 2023-08-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_alter_entry_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="coupon",
            field=models.CharField(default="coupon", max_length=20),
        ),
    ]
