# Generated by Django 4.1.7 on 2023-08-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_category_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="marketplace/categories"
            ),
        ),
    ]
