# Generated by Django 4.1.7 on 2023-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0008_specialoffer_useroffer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_name_en",
            new_name="product_name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_name_ar",
        ),
        migrations.AlterField(
            model_name="product",
            name="coupon",
            field=models.CharField(default="DropMe", max_length=20),
        ),
    ]
