# Generated by Django 4.1.7 on 2023-09-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0009_rename_product_name_en_product_product_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
