# Generated by Django 4.1.7 on 2024-10-26 09:23

import django.core.validators
from django.db import migrations, models
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_alter_wishlist_unique_together_wishlist_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=marketplace.models.upload_to_imgs, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'svg'])]),
        ),
    ]
