# Generated by Django 4.1.7 on 2024-11-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_specialoffer_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/products/thumbnails'),
        ),
    ]
