# Generated by Django 4.1.7 on 2024-11-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
