# Generated by Django 4.1.7 on 2023-02-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_usermodel_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='username',
            field=models.CharField(default='mariam', max_length=50),
            preserve_default=False,
        ),
    ]
