# Generated by Django 4.1.7 on 2023-02-28 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_locationmodel_usermodel_gender_usermodel_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users_api.locationmodel'),
            preserve_default=False,
        ),
    ]
