# Generated by Django 4.1.7 on 2023-03-09 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0007_alter_locationmodel_address_alter_usermodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_api.locationmodel'),
        ),
    ]
