# Generated by Django 4.1.7 on 2023-03-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_api", "0009_delete_resetpasswordmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="points",
        ),
        migrations.AddField(
            model_name="usermodel",
            name="total_points",
            field=models.PositiveIntegerField(
                default=0, help_text="User total earned points"
            ),
        ),
    ]
