# Generated by Django 4.1.7 on 2023-03-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0011_alter_usermodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='test',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
