# Generated by Django 4.1.7 on 2023-03-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_api", "0011_alter_usermodel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="profile_photo",
            field=models.ImageField(default=None, upload_to="upload_to"),
        ),
    ]
