# Generated by Django 4.1.7 on 2023-03-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0012_usermodel_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='test',
        ),
    ]
