# Generated by Django 4.1.7 on 2023-03-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_api", "0012_alter_usermodel_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="profile_photo",
            field=models.ImageField(default="default.jpg", upload_to="upload_to"),
        ),
    ]
