# Generated by Django 4.1.7 on 2023-03-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_api", "0013_alter_usermodel_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="profile_photo",
            field=models.ImageField(
                default="upload_to/default.jpg", upload_to="upload_to"
            ),
        ),
    ]
