# Generated by Django 4.1.7 on 2023-04-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0013_remove_usermodel_test'),
        ('users_api', '0016_alter_usermodel_phone_number'),
    ]

    operations = [
    ]
