# Generated by Django 4.1.7 on 2023-04-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0017_merge_20230409_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
