# Generated by Django 4.1.7 on 2023-04-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0017_merge_20230411_1640'),
        ('users_api', '0018_usermodel_age'),
    ]

    operations = [
    ]
