# Generated by Django 4.1.7 on 2023-04-24 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('users_api', '0019_merge_0017_merge_20230411_1640_0018_usermodel_age'),
        ('users_api', '0002_alter_usermodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_name', to='users_api.locationmodel'),
        ),
    ]
