# Generated by Django 4.1.7 on 2023-05-27 15:20

from django.db import migrations, models
import users_api.models


class Migration(migrations.Migration):

    dependencies = [
        ("users_api", "0020_alter_usermodel_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="profile_photo",
            field=models.ImageField(
                default="upload_to/default.png", upload_to=users_api.models.upload_to
            ),
        ),
    ]
