# Generated by Django 4.1.7 on 2023-08-09 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users_api", "0021_alter_usermodel_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address_name",
                to="users_api.locationmodel",
            ),
        ),
    ]
