# Generated by Django 4.1.7 on 2023-09-26 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_api", "0024_alter_usermodel_total_points"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usermodel",
            options={"ordering": ("-total_points",), "verbose_name": "User"},
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="email",
            field=models.EmailField(
                max_length=50,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Email",
            ),
        ),
    ]
