# Generated by Django 4.1.7 on 2024-10-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0025_alter_usermodel_options_alter_usermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='preferred_language',
            field=models.CharField(choices=[('ARABIC', 'Arabic'), ('ENGLISH', 'English')], default='ENGLISH', max_length=10),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='referral_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='referral_usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
