# Generated by Django 4.1.7 on 2024-10-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0028_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='country_code',
            field=models.CharField(default='+20', max_length=50),
        ),
    ]
