# Generated by Django 4.1.7 on 2024-10-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0029_usermodel_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandcondition',
            name='about_app_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='termsandcondition',
            name='about_app_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='termsandcondition',
            name='privacy_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='termsandcondition',
            name='privacy_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='termsandcondition',
            name='terms_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='termsandcondition',
            name='terms_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
