# Generated by Django 4.1.7 on 2024-10-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0031_remove_termsandcondition_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='app', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
