# Generated by Django 4.1.7 on 2024-10-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0032_feedback_name_feedback_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='oauth_medium',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
