# Generated by Django 4.1.7 on 2024-11-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0034_alter_usermodel_gender_alter_usermodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password_set',
            field=models.BooleanField(default=True),
        ),
    ]
