# Generated by Django 4.1.7 on 2023-04-24 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community_api', '0002_rename_message_messagesmodel_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesmodel',
            name='channel_id',
        ),
        migrations.AddField(
            model_name='channelsmodel',
            name='messages',
            field=models.ManyToManyField(blank=True, to='community_api.messagesmodel'),
        ),
        migrations.AddField(
            model_name='channelsmodel',
            name='participants',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
