# Generated by Django 4.1.7 on 2023-04-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_api', '0003_remove_messagesmodel_channel_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelsmodel',
            old_name='channel_name',
            new_name='room_name',
        ),
        migrations.AlterField(
            model_name='messagesmodel',
            name='content',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
