# Generated by Django 4.1.7 on 2023-05-06 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community_api", "0004_rename_channel_name_channelsmodel_room_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channelsmodel",
            name="participants",
        ),
        migrations.RemoveField(
            model_name="messagesmodel",
            name="emoji",
        ),
        migrations.AlterField(
            model_name="channelsmodel",
            name="room_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="messagesmodel",
            name="content",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="messagesmodel",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="community/imgs"),
        ),
        migrations.AlterField(
            model_name="messagesmodel",
            name="user_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="messagesmodel",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="community/videos"),
        ),
    ]
