# Generated by Django 4.1.7 on 2023-05-07 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community_api", "0005_remove_channelsmodel_participants_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messagesmodel",
            options={"ordering": ("-message_dt",)},
        ),
        migrations.AlterField(
            model_name="messagesmodel",
            name="img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="community/imgs",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpeg", "jpg", "svg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="messagesmodel",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="community/videos",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["MOV", "avi", "mp4", "webm", "mkv"]
                    )
                ],
            ),
        ),
    ]
