# Generated by Django 4.1.7 on 2023-05-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "community_api",
            "0006_alter_messagesmodel_options_alter_messagesmodel_img_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="messagesmodel",
            name="reactions",
            field=models.JSONField(default=dict),
        ),
    ]
