# Generated by Django 4.1.7 on 2023-05-27 15:20

import community_api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community_api", "0007_messagesmodel_reactions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagesmodel",
            name="img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=community_api.models.messages_upload_to_imgs,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpeg", "jpg", "svg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="messagesmodel",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=community_api.models.messages_upload_to_videos,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["MOV", "avi", "mp4", "webm", "mkv"]
                    )
                ],
            ),
        ),
    ]
