# Generated by Django 4.1.7 on 2023-08-09 13:38

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community_api", "0009_reportmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelsmodel",
            name="channel_type",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="channelsmodel",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="channelsmodel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="channelsmodel",
            name="description_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="channelsmodel",
            name="room_name_ar",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="channelsmodel",
            name="users",
            field=models.ManyToManyField(
                related_name="user_channels", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
