# Generated by Django 4.1.7 on 2023-08-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "community_api",
            "0010_channelsmodel_channel_type_channelsmodel_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelsmodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
