# Generated by Django 4.1.7 on 2023-08-09 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community_api", "0011_alter_channelsmodel_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelsmodel",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="user_channels", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
