# Generated by Django 4.1.7 on 2023-08-10 14:51

import community_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community_api", "0012_alter_channelsmodel_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagesmodel",
            name="reactions",
            field=models.JSONField(default=community_api.models.get_default),
        ),
    ]
