# Generated by Django 4.1.7 on 2023-08-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_api', '0014_invitations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsmodel',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='message_channel', to='community_api.messagesmodel'),
        ),
    ]
