# Generated by Django 4.1.7 on 2024-10-25 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community_api', '0015_alter_channelsmodel_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsmodel',
            name='is_admin_channel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channelsmodel',
            name='notification_off_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='notification_off_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagesmodel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
