# Generated by Django 4.1.7 on 2024-10-25 15:57

import community_api.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community_api', '0016_channelsmodel_is_admin_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=4000, null=True)),
                ('comment_dt', models.DateTimeField(auto_now_add=True)),
                ('reactions', models.JSONField(default=community_api.models.get_default)),
                ('img', models.ImageField(blank=True, null=True, upload_to=community_api.models.comments_upload_to_imgs, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'svg'])])),
                ('video', models.FileField(blank=True, null=True, upload_to=community_api.models.comments_upload_to_videos, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('user_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-comment_dt',),
            },
        ),
        migrations.AddField(
            model_name='messagesmodel',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='message_comment', to='community_api.commentsmodel'),
        ),
    ]
