# Generated by Django 4.1.7 on 2024-10-26 20:45

import community_api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_api', '0017_commentsmodel_messagesmodel_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=community_api.models.messages_upload_to_files),
        ),
        migrations.AddField(
            model_name='messagesmodel',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to=community_api.models.messages_upload_to_imgs, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif'])]),
        ),
    ]
