# Generated by Django 4.1.7 on 2023-02-25 13:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Format: required, max = 200 Charachter', max_length=200, verbose_name='Machine name')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('qr_code', models.CharField(help_text='Format : uneditable, get get replaced with each transaction', max_length=500, verbose_name='Machine Qrcode')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
            },
        ),
    ]
